### ISSUE TITLE
Error when referee views dashboard

### ISSUE THREAD

**Issue by NFarrington** [VATSIM-UK/core#530]
In gitlab by @A-Lawrence on Sep 1, 2016, 09:47

#0 /var/www/core/bootstrap/cache/compiled.php(15319): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /var/www/core/bootstrap/cache/compiled.php(15354): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/core/s...', Array)
#2 /var/www/core/bootstrap/cache/compiled.php(15186): Illuminate\View\Engines\CompilerEngine->get('/var/www/core/a...', Array)
#3 /var/www/core/bootstrap/cache/compiled.php(15174): Illuminate\View\View->getContents()
#4 Show more...
Exception:
----------------
ErrorException

Message:
----------------
Missing argument 1 for Carbon\Carbon::addDays(), called in /var/www/core/storage/framework/views/d8f48e61f779d627593427c01221251f2a123ae9.php on line 275 and defined (View: /var/www/core/app/Modules/Visittransfer/Resources/Views/site/dashboard.blade.php)

File:
----------------
/var/www/core/vendor/nesbot/carbon/src/Carbon/Carbon.php

Line:
----------------
1657

Code:
----------------
0

Member:
----------------
1306312 - Brodie Murdoch

Request path:
----------------
https://vt.core.vatsim-uk.co.uk

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Sep 1, 2016, 09:47

Issue due to bad reference (used $application instead of $reference).  Patched on live.

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Sep 1, 2016, 09:48

mentioned in commit 26ef4334f400575fe6e5ca6383839b9030cda7ff

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Sep 1, 2016, 09:49

mentioned in merge request !20
