### ISSUE TITLE
Trying to get property of non-object on SSO Security return

### ISSUE THREAD

**Issue by NFarrington** [VATSIM-UK/core#557]
In gitlab by @A-Lawrence on Sep 5, 2016, 20:21

At the very least we need somebody to investigate why this might be occurring on only _some_ logins.  

Error Handling BOT [21:18]  
ErrorException
#0 /var/www/core/app/Http/Controllers/Sso/Security.php(63): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/var/www/core/a...', 63, Array)
#1 [internal function]: App\Http\Controllers\Sso\Security->postDetails()
#2 /var/www/core/bootstrap/cache/compiled.php(9424): call_user_func_array(Array, Array)
#3 /var/www/core/bootstrap/cache/compiled.php(9486): Illuminate\Routing\Controller->callAction('postDetails', Array)
#4 /var/www/core/bootstrap/cache/compiled.php(9466): Show more...
Exception:
----------------
ErrorException

Message:
----------------
Trying to get property of non-object

File:
----------------
/var/www/core/app/Http/Controllers/Sso/Security.php

Line:
----------------
63

Code:
----------------
0

Request path:
----------------
https://core.vatsim-uk.co.uk/sso/security/details

**Comment by NFarrington** [comment]
Closed - will be addressed when authentication system is overhauled, this is a minor workflow issue that won't affect most users.
